apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-nginx
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 5
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 80
        env:
          - name: "HTTP_PORT"
            value: "81"

      - name: nginx
        image: nginx:1.28
        ports:
        - containerPort: 81
        env:
          - name: "HTTP_PORT"
            value: "80"